### ISSUE TITLE
Missing partial analytical_javascript.html

### ISSUE THREAD

**Issue by dblock** [jkrall/analytical#19]
Rails 3.0.9, analytical 3.0.6.

```
    ActionView::Template::Error (Missing partial /home/dblock/.rvm/gems/ruby-1.9.2-p180/gems/analytical-3.0.6/app/views/application/analytical_javascript.html with {:handlers=>[:erb, :rjs, :builder, :rhtml, :rxml, :haml], :formats=>[:html], :locale=>[:en, :en]} in view paths "/home/dblock/source/gravity/dblock/app/views", "/home/dblock/source/gravity/dblock/vendor/plugins/country_select/app/views", "/home/dblock/.rvm/gems/ruby-1.9.2-p180/gems/analytical-3.0.6/app/views", "/home/dblock/.rvm/gems/ruby-1.9.2-p180/gems/devise_invitable-0.5.2/app/views", "/home/dblock/.rvm/gems/ruby-1.9.2-p180/gems/devise-1.4.2/app/views", "/home/dblock/.rvm/gems/ruby-1.9.2-p180/gems/kaminari-0.12.4/app/views"):
        9:     = include_stylesheets :ipad if ipad_device?
        10:     = include_stylesheets :edit_artwork if current_user.has_authorization_to?(:update, Artwork)
        11:     
        12:     = raw analytical.head_append_javascript
        13: 
        14:   %body
        15:     = raw analytical.body_prepend_javascript
      app/views/layouts/client/main.html.haml:12:in `_app_views_layouts_client_main_html_haml__428043036_126237760__535360229'
      app/controllers/application_controller.rb:32:in `block (3 levels) in <class:ApplicationController>'
      app/controllers/application_controller.rb:31:in `block in <class:ApplicationController>'`
```

**Comment by dblock** [comment]
I'll reopen this with a pull request.

**Comment by dblock** [comment]
There's still an issue. The render is now given the proper path (double checked it exists). It strips .erb from the template and complains.

```
ActionView::Template::Error
     Missing partial /home/dblock/.rvm/gems/ruby-1.9.2-p180/bundler/gems/analytical-67a96495a85a/app/views/application/_analytical_javascript.html with {:handlers=>[:erb, :rjs, :builder, :rhtml, :rxml, :haml], :formats=>[:html], :locale=>[:en, :en]} in view paths "/home/dblock/source/gravity/dblock/app/views", "/home/dblock/source/gravity/dblock/vendor/plugins/country_select/app/views", "/home/dblock/.rvm/gems/ruby-1.9.2-p180/bundler/gems/analytical-67a96495a85a/app/views", "/home/dblock/.rvm/gems/ruby-1.9.2-p180/gems/devise_invitable-0.5.2/app/views", "/home/dblock/.rvm/gems/ruby-1.9.2-p180/gems/devise-1.4.2/app/views", "/home/dblock/.rvm/gems/ruby-1.9.2-p180/gems/kaminari-0.12.4/app/views"
```

**Comment by nirvdrum** [comment]
Are there any known workarounds for this problem?
